services:
    HalloVerden\Oidc\ClientBundle\Interfaces\OpenIdProviderRegistryServiceInterface:
        class: HalloVerden\Oidc\ClientBundle\Services\OpenIdProviderRegistryService
        arguments:
            $openIdProviderServices: !tagged_iterator { tag: 'hv.oidc.openid_provider_service', index_by: 'key' }

    HalloVerden\Security\Interfaces\OauthTokenProviderServiceInterface:
        class: HalloVerden\Oidc\ClientBundle\Services\OauthTokenProviderService

    HalloVerden\Security\Interfaces\OauthJwkSetProviderServiceInterface:
        class: HalloVerden\Oidc\ClientBundle\Services\OauthJwkSetProviderService
        arguments:
            $openIdProviderRegistryService: '@HalloVerden\Oidc\ClientBundle\Interfaces\OpenIdProviderRegistryServiceInterface'
